server:
  port: 8080
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true  

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_URL_PROD}
          predicates:
            - Path=/api/user/**, /api/auth/**
        - id: news-service
          uri: ${NEWS_URL_PROD}
          predicates:
            - Path=/api/news/**, /api/summary/**, /api/scrabs/**
        - id: quiz-service
          uri: ${QUIZ_URL_PROD}
          predicates:
            - Path=/api/quiz/**
        - id: recommendation-service
          uri: ${RECOMMENDATION_URL_PROD}
          predicates:
            - Path=/api/recommendation/**
        - id: ad-service
          uri: ${AD_URL_PROD}
          predicates:
            - Path=/admin/ads/**

jwt:
  secret: ${JWT_SECRET}
