server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - GlobalFilter
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/**
        - id: news-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/news/**
        - id: learning-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/learning/**