server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/**, /api/auth/**
        - id: news-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/news/**
        - id: quiz-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/quiz/**
        - id: recommendation-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/recommendation/**

jwt:
  secret: ${JWT_SECRET}